logging:
  path: /usr/log/exam/

spring:
  redis:
    host: localhost
  datasource:
    url: jdbc:mysql://101.132.110.182:3306/exam?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123
