logging:
  path: ./log/

spring:
  redis:
    host: 192.168.0.96
  datasource:
    url: jdbc:mysql://192.168.0.69:3306/exam?useSSL=false&useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
